lbm/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^sys/', include('system.urls')),
	url(r'^ltm/', include('ltm.urls')),
    url(r'^admin/', admin.site.urls),
	url(r'^/?$', RedirectView.as_view(url='/ltm/', permanent=False), name='index')
]

ltm/urls.py
from django.conf.urls import url

from . import views

app_name = 'ltm'
urlpatterns = [
	url(r'^$', views.index, name='index'),
#	url(r'^node/$', views.NodeIndexView.as_view(), name='node_index'),
	url(r'^node/$', views.node_index, name='node_index'),
#	url(r'^node/(?P<pk>[0-9]+)/$', views.NodeDetailView.as_view(), name='node_detail'),
	url(r'^node/(?P<node_id>[0-9]+)/$', views.node_detail, name='node_detail'),
#	url(r'^pool/$', views.PoolIndexView.as_view(), name='pool_index'),
	url(r'^pool/$', views.pool_index, name='pool_index'),
	url(r'^pool/(?P<pool_id>[0-9]+)/$', views.pool_detail, name='pool_detail'),
#	url(r'^virtual_server/$', views.VirtualServerIndexView.as_view(), name='virtual_server_index'),
	url(r'^virtual_server/$', views.virtualserver_index, name='virtual_server_index'),
#	url(r'^virtual_server/(?P<pk>[0-9]+)/$', views.VirtualServerDetailView.as_view(), name='virtual_server_detail'),
	url(r'^virtual_server/(?P<virtualserver_id>[0-9]+)/$', views.virtualserver_detail, name='virtual_server_detail'),
]

ltm/models.py
from __future__ import unicode_literals

import netaddr

from django.db import models

from system.models import DeviceGroup
from .structures import *

class Node(models.Model):
	name = models.CharField(max_length=255)
	path = models.CharField(max_length=255, default='/Common')
	address = models.GenericIPAddressField()
	state = models.CharField(max_length=200)
	status_availability = models.CharField(max_length=64)
	status_enabled = models.CharField(max_length=64)
	status_description = models.CharField(max_length=255)
#	monitors (many-to-many)
	
	#  Resources
	device_group = models.ForeignKey(DeviceGroup, on_delete=models.CASCADE, blank=True, null=True) #remove blank and null after adjusting data
	
	# Meta
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)
	updated = models.DateTimeField(auto_now=True)
	
	def __str__(self):
		return self.name
	
	def __eq__(self, other):
		return isinstance(other, self.__class__) and self.name == other.name and self.path == other.path and self.device_group == other.device_group
	
	def __ne__(self, other):
		return not isinstance(other, self.__class__) or self.name != other.name or self.path != other.path or self.device_group != other.device_group

class Pool(models.Model):
	#  Properties
	name = models.CharField(max_length=255)
	path = models.CharField(max_length=255, default='/Common')
	state = models.CharField(max_length=200)
	status_availability = models.CharField(max_length=64)
	status_enabled = models.CharField(max_length=64)
	status_description = models.CharField(max_length=255)
	
	#  Methods
	lb_method = models.CharField(max_length=255)
	members = models.ManyToManyField(Node, through='PoolMember')
	
	#  Resources
	device_group = models.ForeignKey(DeviceGroup, on_delete=models.CASCADE, blank=True, null=True) #remove blank and null after adjusting data
	
	# Meta
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)
	updated = models.DateTimeField(auto_now=True)
	
	def __str__(self):
		return self.name
	
	def __eq__(self, other):
		return isinstance(other, self.__class__) and self.name == other.name and self.path == other.path and self.device_group == other.device_group
	
	def __ne__(self, other):
		return not isinstance(other, self.__class__) or self.name != other.name or self.path != other.path or self.device_group != other.device_group

class PoolMember(models.Model):
	#  Properties
	port = models.IntegerField()
	state = models.CharField(max_length=64)
#	monitors
	
	#  Configuration
#	ratio = models.IntegerField()
#	priority_group = models.IntegerField()
#	connection_limit = models.IntegerField()
	
	#  Relationship
	pool = models.ForeignKey(Pool, on_delete=models.CASCADE)
	node = models.ForeignKey(Node, on_delete=models.CASCADE)
	
	# Meta
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)
	updated = models.DateTimeField(auto_now=True)
	
	def __str__(self):
		return self.node.name + ':' + unicode(str(self.port), "utf-8")

class VirtualServerProfile(models.Model):
	name = models.CharField(max_length=255)
	
	def __str__(self):
		return self.name

class VirtualServer(models.Model):
	#  Properties
	name = models.CharField(max_length=255)
	path = models.CharField(max_length=255, default='/Common')
	description = models.CharField(max_length=255)
	vs_type = models.CharField(max_length=64)
#	source = models.CharField(max_length=64)
	destination = models.GenericIPAddressField()
	destination_subnet = models.GenericIPAddressField()
	service_port = models.IntegerField()
	state = models.CharField(max_length=200)
	status_availability = models.CharField(max_length=64)
	status_enabled = models.CharField(max_length=64)
	status_description = models.CharField(max_length=255)
	protocol = models.IntegerField(choices=enumerate(VirtualServerProtocol.PROTOCOLS), default=VirtualServerProtocol.PROTOCOL_TCP)
	
	#  Resources
	pool = models.ForeignKey(Pool, on_delete=models.CASCADE, blank=True, null=True)
	device_group = models.ForeignKey(DeviceGroup, on_delete=models.CASCADE, blank=True, null=True) #remove blank and null after adjusting data
	
	# Meta
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)
	updated = models.DateTimeField(auto_now=True)
	
	def __str__(self):
		return self.name
	
	def __eq__(self, other):
		return isinstance(other, self.__class__) and self.name == other.name and self.path == other.path and self.device_group == other.device_group
	
	def __ne__(self, other):
		return not isinstance(other, self.__class__) or self.name != other.name or self.path != other.path or self.device_group != other.device_group

ltm/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.views import generic
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count

import ltm.structs
from .models import *

def node_index(request):
	node_list = Node.objects.all()
	paginator = Paginator(node_list, 25)

	page = request.GET.get('page')

	try:
		nodes = paginator.page(page)
	except PageNotAnInteger:
		nodes = paginator.page(1)
	except EmptyPage:
		nodes = paginator.page(paginator.num_pages)

	context = {
		'node_list': node_list,
		'nodes': nodes,
	}

	return render(request, 'ltm/node_index.html', context)

def node_detail(request, node_id):
	node = Node.objects.get(pk=node_id)
	active_device = node.device_group.device_set.get(status__contains='active')

	context = {
		'node': node,
		'active_device': active_device,
	}

	return render(request, 'ltm/node_detail.html', context)

def pool_index(request):
	pool_list = [{'id': pool.id, 'name': pool.name, 'method': ltm.structs.lb_method[pool.lb_method]['name'], 'state': pool.state, 'monitor_count': 0, 'member_count': pool.poolmember_set.count(), 'device_group': pool.device_group.name} for pool in Pool.objects.all()]
	paginator = Paginator(pool_list, 25)

	page = request.GET.get('page')

	try:
		pools = paginator.page(page)
	except PageNotAnInteger:
		pools = paginator.page(1)
	except EmptyPage:
		pools = paginator.page(paginator.num_pages)

	context = {
		'pool_list': pool_list,
		'pools': pools,
	}

	return render(request, 'ltm/pool_index.html', context)

def pool_detail(request, pool_id):
	pool = Pool.objects.get(pk=pool_id)
	pool_lb_method = ltm.structs.lb_method[pool.lb_method]['name']
	pool_lb_method_description = ltm.structs.lb_method[pool.lb_method]['description']
	active_device = pool.device_group.device_set.get(status__contains='active')
	member_count = pool.poolmember_set.count()
	members = pool.poolmember_set.all()

	context = {
		'pool': pool,
		'pool_lb_method': pool_lb_method,
		'pool_lb_method_description': pool_lb_method_description,
		'active_device': active_device,
		'member_count': member_count,
		'members': members,
	}

	return render(request, 'ltm/pool_detail.html', context)

def virtualserver_index(request):
	virtual_server_list = VirtualServer.objects.all()

	paginator = Paginator(virtual_server_list, 25)

	page = request.GET.get('page')

	try:
		virtual_servers = paginator.page(page)
	except PageNotAnInteger:
		virtual_servers = paginator.page(1)
	except EmptyPage:
		virtual_servers = paginator.page(paginator.num_pages)

	context = {
#		'virtual_server_list': virtual_server_list,
		'virtual_servers': virtual_servers,
	}

	return render(request, 'ltm/virtualserver_index.html', context)

def virtualserver_detail(request, virtualserver_id):
	virtual_server = VirtualServer.objects.get(pk=virtualserver_id)
	pool_meta = {
		'lb_method_name': ltm.structs.lb_method[virtual_server.pool.lb_method]['name'],
		'lb_method_description': ltm.structs.lb_method[virtual_server.pool.lb_method]['description'],
	}
	active_device = virtual_server.device_group.device_set.get(status__contains='active')
	member_count = virtual_server.pool.poolmember_set.count()
	pool_members = virtual_server.pool.poolmember_set.all()

	context = {
		'virtual_server': virtual_server,
		'active_device': active_device,
		'pool': virtual_server.pool,
		'pool_meta': pool_meta,
		'member_count': member_count,
		'members': pool_members,
	}

	return render(request, 'ltm/virtualserver_detail.html', context)

def index(request):
	#  VirtualServer stats
	virtual_server_list = VirtualServer.objects.all()
	virtual_server_stat_list = virtual_server_list.values('status_availability').annotate(count=Count('status_availability'))
	virtual_server_stats = {key: 0 for key in ltm.structs.availability_status.keys()}
	virtual_server_stats['total'] = 0
	for stat in virtual_server_stat_list:
		virtual_server_stats[stat['status_availability']] = stat['count']
		virtual_server_stats['total'] += stat['count']

	#  Pool stats
	pool_list = Pool.objects.all()
	pool_stat_list = pool_list.values('status_availability').annotate(count=Count('status_availability'))
	pool_stats = {key: 0 for key in ltm.structs.availability_status.keys()}
	pool_stats['total'] = 0
	for stat in pool_stat_list:
		pool_stats[stat['status_availability']] = stat['count']
		pool_stats['total'] += stat['count']

	#  Node stats
	node_list = Node.objects.all()
	node_stat_list = node_list.values('status_availability').annotate(count=Count('status_availability'))
	node_stats = {key: 0 for key in ltm.structs.availability_status.keys()}
	node_stats['total'] = 0
	for stat in node_stat_list:
		node_stats[stat['status_availability']] = stat['count']
		node_stats['total'] += stat['count']

	context = {
		'virtual_server_stats': virtual_server_stats,
#		'virtual_server_list': virtual_server_list,
		'pool_stats': pool_stats,
#		'pool_list': pool_list,
		'node_stats': node_stats,
#		'node_list': node_list,
	}

	return render(request, 'ltm/index.html', context)

ltm/templates/ltm/index.html
{% extends 'base.html' %}
{% block content %}
{% load staticfiles %}
<div class="panel panel-default">
	<div class="panel-heading"><h3 class="panel-title">Statistics</h3></div>
	<table class="table table-striped table-hover table-condensed">
		<thead>
			<tr>
				<th>Type</th>
				<th>Total</th>
				<th><span class="glyphicon glyphicon-ok-sign" style="color: #3c763d;" aria-hidden="true"></span> Available</th>
				<th><span class="glyphicon glyphicon-exclamation-sign" style="color: #8a6d3b;" aria-hidden="true"></span> Unavailable</th>
				<th><span class="glyphicon glyphicon-remove-sign" style="color: #a94442;" aria-hidden="true"></span> Offline</th>
				<th><span class="glyphicon glyphicon-question-sign" style="color: #31708f;" aria-hidden="true"></span> Unknown</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>Virtual Servers</td>
				<td><span class="badge">{{ virtual_server_stats.total }}</span></td>
				<td><span class="badge" style="color: #dff0d8; background-color: #3c763d;">{{ virtual_server_stats.AVAILABILITY_STATUS_GREEN }}</span></td>
				<td><span class="badge" style="color: #fcf8e3; background-color: #8a6d3b;">{{ virtual_server_stats.AVAILABILITY_STATUS_YELLOW }}</span></td>
				<td><span class="badge" style="color: #f2dede; background-color: #a94442;">{{ virtual_server_stats.AVAILABILITY_STATUS_RED }}</span></td>
				<td><span class="badge" style="color: #d9edf7; background-color: #31708f;">{{ virtual_server_stats.AVAILABILITY_STATUS_BLUE }}</span></td>
			</tr>
			<tr>
				<td>Pools</td>
				<td><span class="badge">{{ pool_stats.total }}</span></td>
				<td><span class="badge" style="color: #dff0d8; background-color: #3c763d;">{{ pool_stats.AVAILABILITY_STATUS_GREEN }}</span></td>
				<td><span class="badge" style="color: #fcf8e3; background-color: #8a6d3b;">{{ pool_stats.AVAILABILITY_STATUS_YELLOW }}</span></td>
				<td><span class="badge" style="color: #f2dede; background-color: #a94442;">{{ pool_stats.AVAILABILITY_STATUS_RED }}</span></td>
				<td><span class="badge" style="color: #d9edf7; background-color: #31708f;">{{ pool_stats.AVAILABILITY_STATUS_BLUE }}</span></td>
			</tr>
			<tr>
				<td>Nodes</td>
				<td><span class="badge">{{ node_stats.total }}</span></td>
				<td><span class="badge" style="color: #dff0d8; background-color: #3c763d;">{{ node_stats.AVAILABILITY_STATUS_GREEN }}</span></td>
				<td><span class="badge" style="color: #fcf8e3; background-color: #8a6d3b;">{{ node_stats.AVAILABILITY_STATUS_YELLOW }}</span></td>
				<td><span class="badge" style="color: #f2dede; background-color: #a94442;">{{ node_stats.AVAILABILITY_STATUS_RED }}</span></td>
				<td><span class="badge" style="color: #d9edf7; background-color: #31708f;">{{ node_stats.AVAILABILITY_STATUS_BLUE }}</span></td>
			</tr>
		</tbody>
	</table>
</div>


{% endblock content %}

ltm/templates/ltm/node_index.html
{% extends 'base.html' %}
{% block content %}
{% include 'ltm/node_list.html' %}
{% endblock content %}

ltm/templates/ltm/node_list.html
{% load bootstrap3 %}
{% load staticfiles %}
	<div class="panel panel-default">
		<div class="panel-heading"><h3 class="panel-title">Nodes</h3></div>
		{% if node_list %}
		<table class="table table-striped table-hover table-condensed">
			<thead>
				<tr>
					<th>&nbsp;</th>
					<th>Name</th>
					<th>Address</th>
					{# <th>Monitors</th> #}
					{# <th>Device Group</th> #}
				<tr>
			</thead>
			<tbody>
			{% for node in nodes %}
				<tr class="table-row-clickable" data-href="{% url 'ltm:node_detail' node.id %}">
					<td class="text-right" width="1%"><img src="{% static "images/"|add:node.state|add:".gif" %}" /></td>
					<td>{{ node.name }}</td>
					<td>{{ node.address }}</td>
					{# <td>{{ node.monitor_count }}</td> #}
					{# <td>{{ node.device_group.name }}</td> #}
				</tr>
			{% endfor %}
			</tbody>
		</table>
		<div class="panel-body">
			{% bootstrap_pagination nodes %}
		</div>
		{% else %}
		<div class="panel-body"><p>No nodes found.</p></div>
		{% endif %}
	</div>

ltm/templates/ltm/pool_detail.html
{% extends 'base.html' %}
{% block content %}
{% load staticfiles %}

<h1>{{ pool.name }} <small>Pool</small></h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class="panel panel-default">
	<div class="panel-heading" data-toggle="collapse" href="#pool-properties-panel-body" aria-expanded="false" aria-controls="pool-properties-panel-body">
		<h3 class="panel-title">Properties</h3>
	</div>
	<div class="panel-collapse collapse in" id="pool-properties-panel-body">
		<div class="panel-body">
			<dl class="dl-horizontal">
				<dt>Name:</dt>
				<dd>{{ pool.name }}</dd>
				<dt>Device Group:</dt>
				<dd>{{ pool.device_group.name }} &raquo; <img src="{% static "images/"|add:active_device.status|add:".gif" %}" /> {{ active_device.name }}</dd>
				<dt>Partition / Path:</dt>
				<dd>{{ pool.path }}</dd>
				<dt>Method:</dt>
				<dd><a href="#" data-toggle="tooltip" data-placement="right" title="{{ pool_lb_method_description }}">{{ pool_lb_method }}</a></dd>
				<dt>Priority Group:</dt>
				<dd>Disabled|Less than ## Available Member(s)</dd>
				<dt>Availability:</dt>
				<dd><img src="{% static "images/"|add:pool.state|add:".gif" %}" /></dd>
				<dt>Monitors:</dt>
				<dd>Requires all|at least ## Health Monitor(s)
					<ul>
						<li>standard-http-html</li>
						<li>tcp</li>
					</ul>
				</dd>
			</dl>
			{% if member_count > 0 %}
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Members</h3>
				</div>
				<table class="table table-striped table-hover table-condensed">
					<tr>
						<th>&nbsp;</th>
						<th>Member</th>
						<th>Node Name</th>
						<th>Ratio</th>
						<th>Priority Group</th>
						{# if monitor count > 1 #}<th>Monitors</th>
					</tr>
					{% for member in members %}
					<tr>
						<td class="text-right" width="1%"><img src="{% static "images/"|add:member.state|add:".gif" %}" /></td>
						<td>{{ member.node.address }}:{{ member.port }}</td>
						<td><a href="{% url 'ltm:node_detail' member.node.id %}">{{ member.node.name }}</a></td>
						<td>1</td>
						<td>0</td>
						{# if monitor count > 1 #}<td>
							<img src="{% static "images/status_circle_green.gif" %}" alt="standard-http-html"/>
							<img src="{% static "images/status_diamond_red.gif" %}" alt="tcp"/>
						</td>
					</tr>
					{% endfor %}
				</table>
			</div>
			{% endif %}
		</div>
	</div>
</div>
{% endblock content %}

ltm/templates/ltm/pool_index.html
{% extends 'base.html' %}
{% block content %}
{% include 'ltm/pool_list.html' %}
{% endblock content %}

ltm/templates/ltm/pool_list.html
{% load bootstrap3 %}
{% load staticfiles %}
	<div class="panel panel-default">
		<div class="panel-heading"><h3 class="panel-title">Pools</h3></div>
		{% if pools %}
		<table class="table table-striped table-hover table-condensed">
			<thead>
				<tr>
					<th>&nbsp;</th>
					<th>Name</th>
					<th>Method</th>
					<th>Monitors</th>
					<th>Members</th>
					<th>Device Group</th>
				<tr>
			</thead>
			<tbody>
			{% for pool in pools %}
				<tr class="table-row-clickable" data-href="{% url 'ltm:pool_detail' pool.id %}">
					<td class="text-right" width="1%"><img src="{% static "images/"|add:pool.state|add:".gif" %}" /></td>
					<td>{{ pool.name }}</td>
					<td>{{ pool.method }}</td>
					<td>{{ pool.monitor_count }}</td>
					<td>{{ pool.member_count }}</td>
					<td>{{ pool.device_group }}</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
		<div class="panel-body">
			{% bootstrap_pagination pools %}
		</div>
		{% else %}
		<div class="panel-body"><p>No pools found.</p></div>
		{% endif %}
	</div>

ltm/templates/ltm/virtualserver_detail.html
{% extends 'base.html' %}
{% block content %}
{% load staticfiles %}

<h1>{{ virtual_server.name }} <small>Virtual Server</small></h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class="panel panel-default">
	<div class="panel-heading" data-toggle="collapse" href="#virtual_server-properties-panel-body" aria-expanded="false" aria-controls="profiles-panel-body">
		<h3 class="panel-title">Properties</h3>
	</div>
	<div class="panel-collapse collapse in" id="virtual_server-properties-panel-body">
		<div class="panel-body">
			<dl class="dl-horizontal">
				<dt>Name:</dt>
				<dd>{{ virtual_server.name }}</dd>
				<dt>Device Group:</dt>
				<dd>{{ virtual_server.device_group.name }} &raquo; <img src="{% static "images/"|add:active_device.status|add:".gif" %}" /> {{ active_device.name }}</dd>
{% comment "future" %}
				<dt>Partition / Path:</dt>
				<dd>{{ virtual_server.path }}</dd>
				<dt>Description:</dt>
				<dd>{{ virtual_server.description }}</dd>
				<dt>Type:</dt>
				<dd>{{ virtual_server.type }}</dd>
{% endcomment %}
				<dt>Destination:</dt>
				<dd>{{ virtual_server.destination }}</dd>
{% comment "future" %}
				<dt>Protocol:</dt>
				<dd></dd>
{% endcomment %}
				<dt>Service Port:</dt>
				<dd>{{ virtual_server.service_port }}</dd>
				<dt>Availability:</dt>
				<dd><img src="{% static "images/"|add:virtual_server.state|add:".gif" %}" /></dd>
				<dt>Features:</dt>
				<dd>
					<h4>
						<span class="label label-default">X-Forwarded-For</span>
						<span class="label label-default">SSL Offload</span>
					</h4>
				</dd>
			</dl>
		</div>
	</div>
</div>
<div class="panel panel-default">
	<div class="panel-heading" data-toggle="collapse" href="#virtual_server-profiles-panel-body" aria-expanded="false" aria-controls="virtual_server-profiles-panel-body">
		<h3 class="panel-title">Profiles</h3>
	</div>
	<div class="panel-collapse collapse in" id="virtual_server-profiles-panel-body">
		<div class="panel-body">
			<dl class="dl-horizontal">
				<dt><small>Client</small> Protocol:</dt>
				<dd></dd>
				<dt><small>Server</small> Protocol:</dt>
				<dd></dd>
				<dt>HTTP:</dt>
				<dd></dd>
				<dt><small>Client</small> SSL/TLS:</dt>
				<dd></dd>
				<dt><small>Server</small> SSL/TLS:</dt>
				<dd></dd>
				<dt>SNAT:</dt>
				<dd></dd>
				<dt>OneConnect:</dt>
				<dd></dd>
				<dt>Compression:</dt>
				<dd></dd>
				<dt>Acceleration:</dt>
				<dd></dd>
				<dt>Persistence:<br /><small>(Default/Fallback)</small></dt>
				<dd></dd>
			</dl>
		</div>
	</div>
</div>
<div class="panel panel-default">
	<div class="panel-heading" data-toggle="collapse" href="#virtual_server-pool-panel-body" aria-expanded="false" aria-controls="virtual_server-pool-panel-body">
		<h3 class="panel-title">Pool</h3>
	</div>
	<div class="panel-collapse collapse in" id="virtual_server-pool-panel-body">
		<div class="panel-body">
			<dl class="dl-horizontal">
				<dt>Name:</dt>
				<dd><a href="{% url 'ltm:pool_detail' virtual_server.pool.id %}">{{ pool.name }}</a></dd>
				<dt>Method:</dt>
				<dd><a href="#" data-toggle="tooltip" data-placement="right" title="{{ pool_meta.lb_method_description }}">{{ pool_meta.lb_method_name }}</a></dd>
				<dt>Priority Group:</dt>
				<dd>Disabled|Less than ## Available Member(s)</dd>
				<dt>Availability:</dt>
				<dd><img src="{% static "images/"|add:pool.state|add:".gif" %}" /></dd>
				<dt>Monitors:</dt>
				<dd>Requires all|at least ## Health Monitor(s)
					<ul>
						<li>standard-http-html</li>
						<li>tcp</li>
					</ul>
				</dd>
			</dl>
			{% if member_count > 0 %}
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Members</h3>
				</div>
				<table class="table table-striped table-hover table-condensed">
					<tr>
						<th>&nbsp;</th>
						<th>Member</th>
						<th>Node Name</th>
						<th>Ratio</th>
						<th>Priority Group</th>
						{# if monitor count > 1 #}<th>Monitors</th>
					</tr>
					{% for member in members %}
					<tr>
						<td class="text-right" width="1%"><img src="{% static "images/"|add:member.state|add:".gif" %}" /></td>
						<td>{{ member.node.address }}:{{ member.port }}</td>
						<td><a href="{% url 'ltm:node_detail' member.node.id %}">{{ member.node.name }}</a></td>
						<td>1</td>
						<td>0</td>
						{# if monitor count > 1 #}<td>
							<img src="{% static "images/status_circle_green.gif" %}" alt="standard-http-html"/>
							<img src="{% static "images/status_diamond_red.gif" %}" alt="tcp"/>
						</td>
					</tr>
					{% endfor %}
				</table>
			</div>
			{% endif %}
		</div>
	</div>
</div>
<div class="panel panel-default">
	<div class="panel-heading" data-toggle="collapse" href="#virtual_server-irules-panel-body" aria-expanded="false" aria-controls="virtual_server-irules-panel-body">
		<h3 class="panel-title">iRules</h3>
	</div>
	<div class="panel-collapse collapse" id="virtual_server-irules-panel-body">
		<div class="panel-body">
			Coming soon!
		</div>
	</div>
</div>
<div class="panel panel-default">
	<div class="panel-heading" data-toggle="collapse" href="#virtual_server-policies-panel-body" aria-expanded="false" aria-controls="virtual_server-policies-panel-body">
		<h3 class="panel-title">Policies</h3>
	</div>
	<div class="panel-collapse collapse" id="virtual_server-policies-panel-body">
		<div class="panel-body">
			Coming soon!
		</div>
	</div>
</div>
{% endblock content %}

ltm/templates/ltm/virtualserver_list.html
{% load bootstrap3 %}
{% load staticfiles %}
	<div class="panel panel-default">
		<div class="panel-heading"><h3 class="panel-title">Virtual Servers</h3></div>
		{% if virtual_servers %}
		<table class="table table-striped table-hover table-condensed">
			<thead>
				<tr>
					<th>&nbsp;</th>
					<th>Name</th>
					<th>Destination</th>
					<th>Service Port</th>
					<th>Pool</th>
					<th>Device Group</th>
				</tr>
			</thead>
			<tbody>
			{% for virtual_server in virtual_servers %}
				<tr class="table-row-clickable" data-href="{% url 'ltm:virtual_server_detail' virtual_server.id %}">
					<td class="text-right" width="1%"><img src="{% static "images/"|add:virtual_server.state|add:".gif" %}" /></td>
					<td>{{ virtual_server.name }}</td>
					<td>{{ virtual_server.destination }}</td>
					<td>{{ virtual_server.service_port }}</td>
					<td>{{ virtual_server.pool.name }}</td>
					<td>{{ virtual_server.device_group.name }}</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
		<div class="panel-body">
			{% bootstrap_pagination virtual_servers %}
		</div>
		{% else %}
		<div class="panel-body"><p>No virtual servers found.</p></div>
		{% endif %}
	</div>