lbm/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^sys/', include('system.urls')),
	url(r'^ltm/', include('ltm.urls')),
    url(r'^admin/', admin.site.urls),
	url(r'^/?$', RedirectView.as_view(url='/ltm/', permanent=False), name='index')
]

system/urls.py
from django.conf.urls import url

from . import views

app_name = 'system'
urlpatterns = [
	url(r'^device_group/$', views.devicegroup_index, name='device_group_index'),
	url(r'^device_group/(?P<devicegroup_id>[0-9]+)/$', views.devicegroup_detail, name='device_group_detail'),
	url(r'^device/$', views.device_index, name='device_index'),
	url(r'^device/(?P<device_id>[0-9]+)/$', views.device_detail, name='device_detail'),
	url(r'^device/(?P<device_id>[0-9]+)/test/$', views.device_test, name='device_test'),
	url(r'^export/$', views.devicegroup_generate_inventory, name='devicegroup_generate_inventory'),
]

system/models.py
from __future__ import unicode_literals

from django.db import models

class DeviceGroup(models.Model):
	F5_BIGIP = 'F5 BIG-IP'
	DEVICE_TYPES = (
		(F5_BIGIP, 'F5 BIG-IP'),
	)
	
	name = models.CharField(max_length=200)
	classification = models.CharField(
		max_length=200,
		choices = DEVICE_TYPES,
		default = F5_BIGIP
	)
	
	# Meta
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)
	
	def __str__(self):
		return self.name

class Device(models.Model):
	F5_BIGIP = 'F5 BIG-IP'
	DEVICE_TYPES = (
		(F5_BIGIP, 'F5 BIG-IP'),
	)
	
	name = models.CharField(max_length=200)
	classification = models.CharField(
		max_length=200,
		choices = DEVICE_TYPES,
		default = F5_BIGIP
	)
	version = models.CharField(max_length=32)
	connection = models.CharField(
		max_length=200,
		default = 'bigsuds'
	)
	status = models.CharField(max_length=64, null=True)
	device_group = models.ForeignKey(DeviceGroup, on_delete=models.PROTECT)
	
	# Connection
	hostname = models.CharField(max_length=200)
	username = models.CharField(max_length=64)
	password = models.CharField(max_length=64)
	
	# Meta
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)
	updated = models.DateTimeField(auto_now=True)
	
	def __str__(self):
		return self.name

system/views.py
import os
import json

import bigsuds

from django.core import serializers
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views import generic
from django.utils import timezone

from .models import Device, DeviceGroup
from ltm.models import Node, Pool, PoolMember, VirtualServer

def devicegroup_index(request):
	device_group_list = DeviceGroup.objects.all()
	
	context = {
		'device_group_list': device_group_list,
	}
	
	return render(request, 'system/devicegroup_index.html', context)

def devicegroup_detail(request, devicegroup_id):
	device_group = DeviceGroup.objects.get(pk=devicegroup_id)
	device_count = device_group.device_set.count()
	device_list = device_group.device_set.get_queryset()
	
	context = {
		'device_group': device_group,
		'device_count': device_count,
		'device_list': device_list,
	}
	
	return render(request, 'system/devicegroup_detail.html', context)

def device_index(request):
	device_list = Device.objects.all()
	
	context = {
		'device_list': device_list,
	}
	
	return render(request, 'system/device_index.html', context)

def device_detail(request, device_id):
	device = Device.objects.get(pk=device_id)
	
	context = {
		'device': device,
	}
	
	return render(request, 'system/device_detail.html', context)

def device_test(request, device_id):
	device = Device.objects.get(pk=device_id)
	alerts = []
	
	try:
		conn = bigsuds.BIGIP(device.hostname, device.username, device.password)
		device.status = conn.Management.Device.get_failover_state([device.hostname])[0].lower().replace('ha_state','status_device')
		device.version = conn.System.SystemInfo.get_version()[8:]
		device.updated = timezone.now()
		
		device.save()
		alerts.append({'alert_type': 'success', 'content': "Connection to "+device.name+" successful, "+device.status[14:]+" running "+device.version})
	except Exception, e:
		alerts.append({'alert_type': 'danger', 'content': "Connection to "+device.name+" failed, "+e.message})
	
	context = {
		'device': device,
		'alerts': alerts,
	}
	
	return render(request, 'alerts.html', context)

def connect(device):
	if type(device) != Device:
		#  Throw error and exit
		return None
	
	connection = None
	try:
		connection = bigsuds.BIGIP(device.hostname, device.username, device.password)
		connection = connection.with_session_id()
	except Exception, e:
		pass
	
	return connection

def discover(device_group):
	#  Constants
	status_indicators = {
		'AVAILABILITY_STATUS_GREEN': 'status_circle_green',
		'AVAILABILITY_STATUS_YELLOW': 'status_triangle_yellow',
		'AVAILABILITY_STATUS_RED': 'status_diamond_red',
		'AVAILABILITY_STATUS_BLUE': 'status_square_blue',
		'AVAILABILITY_STATUS_GRAY': 'status_square_gray',
	}
	
	if type(device_group) != DeviceGroup:
		#  Throw error and exit
		return None
	
	#  Connect to active BIG-IP in DeviceGroup
	active_device = device_group.device_set.get(status__contains='active')
	connection = connect(active_device)
	
	#  Get list of virtual servers, pools, and nodes from device
#	device_virtual_servers = connection.LocalLB.VirtualServer.get_list()
	
	#####  Node  #####
	device_node_list = []
	device_node_addresses = []
	
	device_node_statuses = []
	if active_device.version >= '11.0.0':
		device_node_list = connection.LocalLB.NodeAddressV2.get_list()
		device_node_addresses = connection.LocalLB.NodeAddressV2.get_address(device_node_list)
		device_node_statuses = connection.LocalLB.NodeAddressV2.get_object_status(device_node_list)
	else:
		device_node_list = connection.LocalLB.NodeAddress.get_list()
		device_node_addresses = device_node_list
		device_node_names = connection.LocalLB.NodeAddress.get_screen_name(device_node_addresses)
		#  If name exists (is not empty) replace address in list with name
		for i in range(len(device_node_list)):
			if device_node_names[i]:
				device_node_list[i] = device_node_names[i]
		device_node_statuses = connection.LocalLB.NodeAddress.get_object_status(device_node_addresses)
	
	#  Build Node object list from device data
	device_nodes = [{'name': unicode(os.path.basename(nodename), "utf-8"), 'path': unicode(os.path.dirname(nodename), "utf-8"), 'device_group': device_group} for nodename in device_node_list]
	
	#  Synchronize device nodes with database list
	for i, node in enumerate(device_nodes):
		try:
			#  Try updating the record by getting Node from DB
			item = Node.objects.get(**node)
			
			#  Update node with other attributes before setting to DB
			node['address'] = device_node_addresses[i]
			node['status_availability'] = device_node_statuses[i]['availability_status']
			node['status_enabled'] = device_node_statuses[i]['enabled_status']
			node['status_description'] = device_node_statuses[i]['status_description']
			
			#  Compute state for icon based on statuses
			node['state'] = status_indicators[device_node_statuses[i]['availability_status']]
			if node['status_enabled'] == 'ENABLED_STATUS_DISABLED':
				node['state'] = node['state'].replace('green', 'black').replace('red', 'black')
			
			#  Add Device values to DB object
			for key, value in node.iteritems():
				setattr(item, key, value)
			
			#  Save to DB
			item.save()
			
		except Node.DoesNotExist:
			#  Update failed, create new
			
			#  Update node with other attributes before setting to DB
			node['address'] = device_node_addresses[i]
			node['status_availability'] = device_node_statuses[i]['availability_status']
			node['status_enabled'] = device_node_statuses[i]['enabled_status']
			node['status_description'] = device_node_statuses[i]['status_description']
			
			#  Compute state for icon based on statuses
			node['state'] = status_indicators[device_node_statuses[i]['availability_status']]
			if node['status_enabled'] == 'ENABLED_STATUS_DISABLED':
				node['state'] = node['state'].replace('green', 'black').replace('red', 'black')
			
			item = Node.objects.create(**node)
			
	#####  Pool  #####
	device_pool_list = connection.LocalLB.Pool.get_list()
	device_pool_lb_methods = connection.LocalLB.Pool.get_lb_method(device_pool_list)
	device_pool_statuses = connection.LocalLB.Pool.get_object_status(device_pool_list)
	device_pool_members = []
	if active_device.version >= '11.0.0':
		device_pool_members = connection.LocalLB.Pool.get_member_v2(device_pool_list)
	else:
		device_pool_members = connection.LocalLB.Pool.get_member(device_pool_list)
	device_pool_member_status = connection.LocalLB.Pool.get_member_object_status(device_pool_list, device_pool_members)
	
	#  Build Pool object list from device data
	device_pools = [{'name': unicode(os.path.basename(poolname), "utf-8"), 'path': unicode(os.path.dirname(poolname), "utf-8"), 'device_group': device_group} for poolname in device_pool_list]
	
	#  Synchronize device pools with database list
	for i, pool in enumerate(device_pools):
		try:
			#  Try updating the record by getting Pool from DB
			item = Pool.objects.get(**pool)
			
			#  Update node with other attributes before setting to DB
			pool['lb_method'] = device_pool_lb_methods[i]
			pool['status_availability'] = device_pool_statuses[i]['availability_status']
			pool['status_enabled'] = device_pool_statuses[i]['enabled_status']
			pool['status_description'] = device_pool_statuses[i]['status_description']
			
			#  Compute state for icon based on statuses
			pool['state'] = status_indicators[device_pool_statuses[i]['availability_status']]
			if pool['status_enabled'] == 'ENABLED_STATUS_DISABLED':
				pool['state'] = pool['state'].replace('green', 'black').replace('red', 'black')
			
			#  Add Device values to DB object
			for key, value in pool.iteritems():
				setattr(item, key, value)
			
			#  Save to DB
			item.save()
			
		except Pool.DoesNotExist:
			#  Update failed, create new
			
			#  Update pool with other attributes before setting to DB
			pool['lb_method'] = device_pool_lb_methods[i]
			pool['status_availability'] = device_pool_statuses[i]['availability_status']
			pool['status_enabled'] = device_pool_statuses[i]['enabled_status']
			pool['status_description'] = device_pool_statuses[i]['status_description']
			
			#  Compute state for icon based on statuses
			pool['state'] = status_indicators[device_pool_statuses[i]['availability_status']]
			if pool['status_enabled'] == 'ENABLED_STATUS_DISABLED':
				pool['state'] = pool['state'].replace('green', 'black').replace('red', 'black')
			
			item = Pool.objects.create(**pool)
			
		#  Update members for pool
		for j, member in enumerate(device_pool_members[i]):
			node = Node.objects.get(name=os.path.basename(member['address']), path=os.path.dirname(member['address']), device_group = device_group)
			member_state = status_indicators[device_pool_member_status[i][j]['availability_status']]
			if device_pool_member_status[i][j]['enabled_status'] == 'ENABLED_STATUS_DISABLED':
				member_state = member_state.replace('green', 'black').replace('red', 'black')
			elif device_pool_member_status[i][j]['enabled_status'] == 'ENABLED_STATUS_DISABLED_BY_PARENT':
				member_state = member_state.replace('green', 'gray').replace('red', 'gray')
			
			try:
				poolmember = item.poolmember_set.get(node__name=unicode(os.path.basename(member['address']), "utf-8"), node__path=unicode(os.path.dirname(member['address']), "utf-8"), port=member['port'])
				setattr(poolmember, 'state', member_state)
				poolmember.save()
			except PoolMember.DoesNotExist:
				PoolMember.objects.create(pool=item, node=node, port=member['port'], state=member_state)
	
	#####  VirtualServer  #####
	device_vs_list = connection.LocalLB.VirtualServer.get_list()
	device_vs_descriptions = connection.LocalLB.VirtualServer.get_description(device_vs_list)
	device_vs_types = connection.LocalLB.VirtualServer.get_type(device_vs_list)
	if active_device.version >= '11.0.0':
		device_vs_destinations = connection.LocalLB.VirtualServer.get_destination_v2(device_vs_list)
	else:
		device_vs_destinations = connection.LocalLB.VirtualServer.get_destination(device_vs_list)

system/templates/system/device_detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
{% load staticfiles %}
<script src="{% static 'scripts/system-device-test.js' %}"></script>

<h1>{{ device.name }} <small>Device</small></h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class="panel panel-default">
	<div class="panel-heading" data-toggle="collapse" href="#device-properties-panel-body" aria-expanded="false" aria-controls="device-properties-panel-body">
		<h3 class="panel-title">Properties</h3>
	</div>
	<div class="panel-collapse collapse in" id="device-properties-panel-body">
		<div class="panel-body">
			<dl class="dl-horizontal">
				<dt>Name:</dt>
				<dd>{{ device.name }}</dd>
				<dt>Classification:</dt>
				<dd>{{ device.classification }}</dd>
				<dt>Connection:</dt>
				<dd>{{ device.connection }}</dd>
				<dt>Version:</dt>
				<dd>{{ device.version }}</dd>
				<dt>Status:</dt>
				<dd><img src="{% static "images/"|add:device.status|add:".gif" %}" /> Text Status</dd>
				<dt>Device Group:</dt>
				<dd><a href="{% url 'system:device_group_detail' device.device_group.id %}">{{ device.device_group.name }}</a></dd>
			</dl>
			<button class="btn btn-primary" role="button" id="system-device-test" data-href="{%url 'system:device_test' device.id %}">{% bootstrap_icon "log-in" %}&nbsp;Test Connection</button>
			{#<a href="{% url 'system:device_test' device.id %}" class="btn btn-primary" role="button">{% bootstrap_icon "log-in" %}&nbsp;Test Connection</a>#}
		</div>
	</div>
</div>
{% endblock content %}

system/templates/system/device_index.html
{% extends 'base.html' %}
{% block content %}
{% include 'system/device_list.html' %}
{% endblock content %}

system/templates/system/device_list.html
{% load staticfiles %}
	<div class="panel panel-default">
		<div class="panel-heading"><h3 class="panel-title">Devices</h3></div>
		{% if device_list %}
		<table class="table table-striped table-hover table-condensed">
			<thead>
				<tr>
					<th>&nbsp;</th>
					<th>Name</th>
					<th>Classification</th>
					<th>Connection</th>
					<th>Version</th>
					<th>Device Group</th>
				<tr>
			</thead>
			<tbody>
			{% for device in device_list %}
				<tr class="table-row-clickable" data-href="{% url 'system:device_detail' device.id %}">
					<td class="text-right" width="1%"><img src="{% static "images/"|add:device.status|add:".gif" %}" /></td>
					<td>{{ device.name }}</td>
					<td>{{ device.classification }}</td>
					<td>{{ device.connection }}</td>
					<td>{{ device.version }}</td>
					<td>{{ device.device_group.name }}</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
		{% else %}
		<div class="panel-body"><p>No device groups found.</p></div>
		{% endif %}
	</div>

system/templates/system/devicegroup_detail.html
{% extends 'base.html' %}
{% block content %}
{% load staticfiles %}

<h1>{{ device_group.name }} <small>Device Group</small></h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<div class="panel panel-default">
	<div class="panel-heading" data-toggle="collapse" href="#device_group-properties-panel-body" aria-expanded="false" aria-controls="device_group-properties-panel-body">
		<h3 class="panel-title">Properties</h3>
	</div>
	<div class="panel-collapse collapse in" id="device_group-properties-panel-body">
		<div class="panel-body">
			<dl class="dl-horizontal">
				<dt>Name:</dt>
				<dd>{{ device_group.name }}</dd>
				<dt>Classification:</dt>
				<dd>{{ device_group.classification }}</dd>
			</dl>
			{% if device_count > 0 %}
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Devices</h3>
				</div>
				<table class="table table-striped table-hover table-condensed">
					<tr>
						<th>&nbsp;</th>
						<th>Name</th>
						<th>Connection</th>
						<th>Version</th>
					</tr>
					{% for device in device_list %}
					<tr>
						<td class="text-right" width="1%"><img src="{% static "images/"|add:device.status|add:".gif" %}" /></td>
						<td><a href="{% url 'system:device_detail' device.id %}">{{ device.name }}</a></td>
						<td>{{ device.connection }}</td>
						<td>{{ device.version }}</td>
					</tr>
					{% endfor %}
				</table>
			{% endif %}
		</div>
	</div>
</div>
{% endblock content %}

system/templates/system/devicegroup_index.html
{% extends 'base.html' %}
{% block content %}
{% include 'system/devicegroup_list.html' %}
{% endblock content %}

system/templates/system/devicegroup_list.html
{% load staticfiles %}
	<script src="{% static 'scripts/system-devicegroup-export.js' %}"></script>
	<div class="panel panel-default">
		<div class="panel-heading"><h3 class="panel-title">Device Groups</h3></div>
		{% if device_group_list %}
		<table class="table table-striped table-hover table-condensed">
			<thead>
				<tr>
					<th>Name</th>
					<th>Classification</th>
				<tr>
			</thead>
			<tbody>
			{% for device_group in device_group_list %}
				<tr class="table-row-clickable" data-href="{% url 'system:device_group_detail' device_group.id %}">
					<td>{{ device_group.name }}</td>
					<td>{{ device_group.classification }}</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
		<div class="panel-body">
			<form class="form-inline">
				<div class="form-group">
					<label for="devicegroup-export-format" class="sr-only">Format</label>
					<select class="form-control selectpicker" style="width: auto; float: left; display: inline-block;" id="devicegroup-export-format">
						<option value="dump" selected>LBOV</option>
						<option value="ansible">Ansible</option>
					</select>
					<button class="btn btn-default btn-primary" type="button"><span class="glyphicon glyphicon-download-alt"></span><span> Export</span></button>
				</div>
			</form>
		</div>
		{% else %}
		<div class="panel-body"><p>No device groups found.</p></div>
		{% endif %}
	</div>