lbm/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^sys/', include('system.urls')),
	url(r'^ltm/', include('ltm.urls')),
    url(r'^admin/', admin.site.urls),
	url(r'^/?$', RedirectView.as_view(url='/ltm/', permanent=False), name='index')
]

ltm/urls.py
from django.conf.urls import url

from . import views

app_name = 'ltm'
urlpatterns = [
	url(r'^$', views.index, name='index'),
#	url(r'^node/$', views.NodeIndexView.as_view(), name='node_index'),
	url(r'^node/$', views.node_index, name='node_index'),
#	url(r'^node/(?P<pk>[0-9]+)/$', views.NodeDetailView.as_view(), name='node_detail'),
	url(r'^node/(?P<node_id>[0-9]+)/$', views.node_detail, name='node_detail'),
#	url(r'^pool/$', views.PoolIndexView.as_view(), name='pool_index'),
	url(r'^pool/$', views.pool_index, name='pool_index'),
	url(r'^pool/(?P<pool_id>[0-9]+)/$', views.pool_detail, name='pool_detail'),
#	url(r'^virtual_server/$', views.VirtualServerIndexView.as_view(), name='virtual_server_index'),
	url(r'^virtual_server/$', views.virtualserver_index, name='virtual_server_index'),
#	url(r'^virtual_server/(?P<pk>[0-9]+)/$', views.VirtualServerDetailView.as_view(), name='virtual_server_detail'),
	url(r'^virtual_server/(?P<virtualserver_id>[0-9]+)/$', views.virtualserver_detail, name='virtual_server_detail'),
]

system/urls.py
from django.conf.urls import url

from . import views

app_name = 'system'
urlpatterns = [
	url(r'^device_group/$', views.devicegroup_index, name='device_group_index'),
	url(r'^device_group/(?P<devicegroup_id>[0-9]+)/$', views.devicegroup_detail, name='device_group_detail'),
	url(r'^device/$', views.device_index, name='device_index'),
	url(r'^device/(?P<device_id>[0-9]+)/$', views.device_detail, name='device_detail'),
	url(r'^device/(?P<device_id>[0-9]+)/test/$', views.device_test, name='device_test'),
	url(r'^export/$', views.devicegroup_generate_inventory, name='devicegroup_generate_inventory'),
]

templates/alerts.html
{% load bootstrap3 %}
		{% for alert in alerts %}
		{% bootstrap_alert alert.content alert_type=alert.alert_type dismissable=True %}
		{% endfor %}

templates/base.html
<!DOCTYPE html>
<html>
{# Load the tag library #}
{% load bootstrap3 %}

{% load staticfiles %}
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Load Balancing Manager</title>
		{% bootstrap_css %}
		<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
		{% bootstrap_javascript jquery=1 %}
		<script src="{% static 'scripts/table-row-clickable.js' %}"></script>
		<script src="{% static 'scripts/tooltips.js' %}"></script>
	</head>

	<body>
		{% include 'navbar.html' %}
		<div class="container" id="alerts">
		{% for message in alerts %}
		{% bootstrap_alert message.content alert_type=message.alert_type dismissable=True %}
		{% endfor %}
		</div>
		<div class="container">
		{% block content %}{% endblock content %}
		</div>
		{#<pre>{% filter force_escape %}{% debug %}{% endfilter %}</pre>#}
	</body>
</html>

templates/navbar.html
{% load bootstrap3 %}
{% load staticfiles %}
		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="container-fluid">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="{% url 'ltm:index' %}">LBM</a>
				</div>

				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li class="active"><a href="{% url 'ltm:index' %}">Home <span class="sr-only">(current)</span></a></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Objects <span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><a href="{% url 'ltm:virtual_server_index' %}">Virtual Servers</a></li>
								<li><a href="#"><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Profiles</small></a></li>
								<li><a href="#"><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;iRules</small></a></li>
								<li><a href="#"><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Policies</small></a></li>
								<li><a href="{% url 'ltm:pool_index' %}">Pools</a></li>
								<li><a href="{% url 'ltm:node_index' %}">Nodes</a></li>
								<li role="separator" class="divider"></li>
								<li><a href="{% url 'system:device_index' %}">Devices</a></li>
								<li><a href="{% url 'system:device_group_index' %}">Device Groups</a></li>
							</ul>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tools <span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><a href="#">Reports</a></li>
							</ul>
						</li>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						<li><a href="{% url 'admin:index' %}"><small>Admin</small></a></li>
					</ul>
					<form class="navbar-form navbar-right" role="search">
						<div class="form-group">
							<div class="input-group">
								<input type="text" class="form-control" placeholder="Search">
								<span class="input-group-btn">
									<button type="submit" class="btn btn-default">{% bootstrap_icon "search" %}</button>
								</span>
							</div>
						</div>
					</form>
				</div><!-- /.navbar-collapse -->
			</div><!-- /.container-fluid -->
		</nav>